### ISSUE TITLE
class content padding not working

### ISSUE THREAD

**Issue by neotune** [erdkse/adminlte-3-vue#43]
hey it's me again

I found the problem again

original adminlte3
![스크린샷 2022-09-22 오후 6 35 19](https://user-images.githubusercontent.com/9148905/191713835-3bf8957a-2d30-481d-82c4-f341b2e3be69.png)

your source
![스크린샷 2022-09-22 오후 6 35 26](https://user-images.githubusercontent.com/9148905/191713919-3fe8a330-e2b5-4b8e-961c-239f5a2db02a.png)

css class .content-wrapper>.content  not working

I think the solution is this

 index.scss line 12 delete
```css
#app {
    width: 100vw; <- this 
    height: 100vh;
}
```

Or Do you have any ideas for a solution?

**Comment by erdkse** [comment]
thanks for reporting, hmm let me check, I will cross try to find a better solution

**Comment by erdkse** [comment]
<img width="1509" alt="Screen Shot 2022-09-22 at 13 16 12" src="https://user-images.githubusercontent.com/2957624/191721516-3fd13e4f-5587-4d78-8bb2-5ea5dfe3527b.png">

It looks perfectly fine for me, Are you sure you didn't add any code to break it? I would like to test it in the same conditions, Can you describe it please?

**Comment by neotune** [comment]
> <img alt="Screen Shot 2022-09-22 at 13 16 12" width="1509" src="https://user-images.githubusercontent.com/2957624/191721516-3fd13e4f-5587-4d78-8bb2-5ea5dfe3527b.png">
> 
> It looks perfectly fine for me, Are you sure you didn't add any code to break it? I would like to test it in the same conditions, Can you describe it please?




You need to lower the height enough to create a scrollbar.
may be less than 300 Height

I downloaded the master branch source and build it.

**Comment by neotune** [comment]
like this

![스크린샷 2022-09-22 오후 7 35 18](https://user-images.githubusercontent.com/9148905/191725349-933a69e5-891b-4035-82a2-a4ba215a5f54.png)

**Comment by neotune** [comment]
Card gets too close to the scrollbar

![스크린샷 2022-09-22 오후 6 35 19](https://user-images.githubusercontent.com/9148905/191726058-cb143ea9-aabf-4fd4-a704-9935e87e6695.png)

![스크린샷 2022-09-22 오후 6 35 26](https://user-images.githubusercontent.com/9148905/191726078-c7cb69a7-b28c-48ca-9c41-1c1fdcffea9a.png)

**Comment by erdkse** [comment]
This should be solved, can you confirm please?

**Comment by tvoSE** [comment]
The problem is not fixed. Deleting with #app.width in index.scss still fixes the scrollbar overlaying the content.
