### ISSUE TITLE
The sidebar crash the web application

### ISSUE THREAD

**Issue by ychevarrias** [erdkse/adminlte-3-vue#50]
The bug makes the web application unable to render the corresponding screen, but the url changes normally

PD: The bug only occurs in production, not in the development environment

[Grabación de pantalla desde 08-09-23 05:32:39.webm](https://github.com/erdkse/adminlte-3-vue/assets/13970636/92591bcd-8e20-483d-b565-bdfc1d3cc582)

**Comment by erdkse** [comment]
Can you try now? It looks like the bug has been fixed @ychevarrias

**Comment by ychevarrias** [comment]
@erdkse  just now I tried the demo of the main branch:
https://adminlte-3-vue-git-main-erdkse.vercel.app/
the error persists 😢

**Comment by erdkse** [comment]
ohh the browser is Firefox I believe, I tried on it and I received the error, thanks

**Comment by erdkse** [comment]
it looks like working, can you test it again and confirm please? @ychevarrias

**Comment by ychevarrias** [comment]
> ohh the browser is Firefox I believe, I tried on it and I received the error, thanks

It's Google Chrome Versión 117.0.5938.88 (Build oficial) (64 bits)

**Comment by ychevarrias** [comment]
The console shows these errors
![image](https://github.com/erdkse/adminlte-3-vue/assets/13970636/22b5397b-3613-4bca-a000-ea66ffa92f3f)

**Comment by PerryCodes** [comment]
Did this ever get fixed?

**Comment by Bloodcasterjavier** [comment]
Don't ask me why, but adding 
```
<div class="content-wrapper">
        <router-view :key="$route.path"></router-view>
    </div>
```
to the main.html file fixes this

the Sub menu 2 shares the same component Blank, with the path Blank, by adding :key="$route.path", it correctly destroys and recreates that component in case it bugs

this error happens only after clicking Sub menu 2, then Blank, so that's how i discovered it hahaha
